### ISSUE TITLE
"Error resolving NetSuite datacenter"

### ISSUE THREAD

**Issue by christopherwxyz** [CrossLead/netsuite-js#2]
Trying to run the node sample.js file with correct credentials, but does not run:

```
Creating Netsuite connection
Error resolving NetSuite datacenter
```

**Comment by yangchristian** [comment]
Thanks for the report. I do need to add more verbose logging, but in the meantime can you add the following line on https://github.com/CrossLead/netsuite-js/blob/master/lib/netsuite/configuration.js#L126 and include what you see? 

``` js
console.debug(json)
```

**Comment by christopherwxyz** [comment]
console.log(json):

```
Creating NetSuite connection
{ error: 
   { code: 'USER_ERROR',
    message: 'Your account is disabled for 23 more minutes due to 6 consecutive failed login attempts.'     } }
```

So I'll need to see _why_ it's been disabled, but it works correctly in-browser.

**Comment by christopherwxyz** [comment]
Update, using a not disabled account, correct username, password, role 3 and full privileges for web services:

```
Creating NetSuite connection
undefined:1
"name":"NetSuite Inc."},"role":{"internalId":30,"name":"NetSuite Support Cente

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/cmw/Documents/Work/SGAP-App/netsuite-js/lib/netsuite/configuration.js:125:25)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:310:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
```

**Comment by yangchristian** [comment]
That stack trace looks like it's pointing to the `JSON.parse()` call on line 125:

``` js
at IncomingMessage.<anonymous> (/Users/cmw/Documents/Work/SGAP-App/netsuite-js/lib/netsuite/configuration.js:125:25)
```

Can `console.log(data)` (instead of `console.log(json)`)? From your output, it looks like you're now getting somewhat correct info from the discovery service.

Background: we're in midst the discovery workflow described under "Understanding the Effects of Accounts' Host Data Center on URLs" on p27 of [SuiteTalk (Web Services) Platform Guide](https://system.na1.netsuite.com/help/helpcenter/en_US/PDF/SuiteTalkWebServicesPlatformGuide.pdf)

**Comment by christopherwxyz** [comment]
I get the exact same error as before, regardless of console.log(data/json)

**Comment by christopherwxyz** [comment]
Sorry, here's the total response (move console.log(data)):

Creating NetSuite connection
[{"account":
{"internalId":"XXX","name":"XXX"},
"role":
{"internalId":1006,"name":"XXX Custom Sales Manager"},
"dataCenterURLs":
{"restDomain":"https://rest.na1.netsuite.com","systemDomain":"https://system.na1.netsuite.com","webservicesDomain":"https://webservices.na1.netsuite.com"}},
{"account":{"internalId":"XXX","name":"XXX"},
"role":{"internalId":3,"name":"Administrator"},
"dataCenterURLs":{"restDomain":"https://rest.netsuite.com","systemDomain":"https://system.netsuite.com","webservicesDomain":"https://webservices.netsuite.com"}},
{"account":{"internalId":"XXX","name":"XXX"},
"role":{"internalId":1011,"name":"XXX - Support Administrator"},
"dataCenterURLs":{"restDomain":"https://rest.netsuite.com","systemDomain":"https://system.netsuite.com","webservicesDomain":"https://webservices.netsuite.com"}},
{"account":{"internalId":"NLCORP","name":"NetSuite Inc."},
"role":{"internalId":30,"name":"NetSuite Support Cente
undefined:1
"name":"NetSuite Inc."},"role":{"internalId":30,"name":"NetSuite Support Cente

**Comment by yangchristian** [comment]
Great, thanks. I can think of 2 potential solutions:
- I might have made an incorrect assumption that the `internalId` returned by the discovery service should match your credential's `account` number. In the uncensored responses, can you verify manually that there is a match? If not, I can lessen the restriction
- Your returned response looks like the service is returning `internalId`s as strings, so this check using `===` will fail:

``` js
          if (config.account && config.account.internalId === accountString) {
```

Can you swap it to `==` operator for now? If one of both of above are true, and I can make a better fix (using `parseInt` or something)

**Comment by yangchristian** [comment]
By the way, I'm on skype as `yang.christian` if it'd be easier to debug over chat

**Comment by christopherwxyz** [comment]
I sent you a message for adding me as a contact. I think the main issue is that the account json has multiple accounts, which is preventing the script from getting to the administrator role. The json is actually incomplete -- it cuts off before Support Center is full described in the "role":{ part.

**Comment by yangchristian** [comment]
Thanks. Sadly I'm a dope and left out a period in my skype username (it's `yang.christian`, not `yangchristian`, fixed original comment). That is also odd that the JSON cuts off - let's figure out over chat if the REST service is not returning a complete response (or the library code is messing up).

**Comment by yangchristian** [comment]
I just pushed d2aeadcb15883c0523a8439eb70ca348a208947d that makes the client work with chunked data. Can you pull and see if that fixes things?

**Comment by christopherwxyz** [comment]
Looks like this works in full -- response is no longer truncated and the example script returns in full. I'll add you on Skype as I make contribs. Thanks for the edits!
