### ISSUE TITLE
Unable to change WSDL version to 2016_1/2

### ISSUE THREAD

**Issue by christopherwxyz** [CrossLead/netsuite-js#5]
So I'm working towards trying to allow the WSDL to be changed to the most recent version, 2016_2 <https://webservices.netsuite.com/wsdl/v2016_2_0/netsuite.wsdl>, and no luck: all my requests send/return 2014_2. Thoughts?

See code below. I also added applicationId functionality, but I don't believe that's being picked up, either:

```var Configuration = module.exports = function Configuration(credentials, options) {
  this.credentials = credentials || {};
  this.options = _.merge({
    apiVersion: '2016_2'
  }, options);

  // Default
  this._webservicesDomain = 'https://webservices.na1.netsuite.com/';
};

/**
 * Static helper for creating NeSuite auth header
 * @param {Object} credentials NetSuite credentials hash
 * @return {Object} SOAP object
 */
Configuration.createAuthHeader = function(credentials) {
  // TODO: refactor into own class
  var soapObj = {
    'platformMsgs:passport': {
      'platformCore:email': credentials.email,
      'platformCore:password': credentials.password,
      'platformCore:account': credentials.account
    },
    'platformMsgs:ApplicationInfo': {
      'platformMsgs:applicationId': credentials.applicationId
      }
  };

  if (credentials.role) {
    soapObj['platformMsgs:passport']['platformCore:role'] = {
      $attributes: {
        'internalId': credentials.role
      }
    };
  }

  return soapObj;
};

**Comment by yangchristian** [comment]
For the WSDL: What does `this._wsdl` return as if you call `_resolveWsdl()` after calling `createAuthHeader()`? For me, it resolves to https://webservices.na1.netsuite.com/wsdl/v2016_2_0/netsuite.wsdl which seems to be right.

For the application id: Haven't actually tried setting it, but from a quick glance at the WSDL, could it be a case sensitivity issue? I see the namespace as `platformMsgs:applicationInfo`.

**Comment by christopherwxyz** [comment]
I actually installed a local and global package, so disregard this issue and close it. I'm going to open another ticket for applicationId -- I got that to work.
